import { ref } from "vue"

export const MAX_COLOUR_COLUMNS = 6

export function isMultiColour(row) {
	return row.kind === "knitting" && !row.reference_routed && row.has_colour
		&& (row.colour_options || []).length > 0
		&& row.colour_options.length <= MAX_COLOUR_COLUMNS
}

const SECTIONABLE_FABRIC_KINDS = ["conversion", "dyeing", "compacting", "identity"]

export function buildColourDiaLayout(row) {
	const qtyRows = row.qty_rows || []
	const sections = []
	const bySection = new Map()
	qtyRows.forEach((qr, j) => {
		const sectionKey = qr.section == null ? " null" : String(qr.section)
		let section = bySection.get(sectionKey)
		if (!section) {
			section = { name: qr.section, items: [], diaGroups: [] }
			section._diaByName = new Map()
			bySection.set(sectionKey, section)
			sections.push(section)
		}
		const item = { qr, j }
		section.items.push(item)
		const diaName = qr.row_label || qr.label || "—"
		let diaGroup = section._diaByName.get(diaName)
		if (!diaGroup) {
			diaGroup = { name: diaName, items: [] }
			section._diaByName.set(diaName, diaGroup)
			section.diaGroups.push(diaGroup)
		}
		diaGroup.items.push(item)
	})
	const sectionable = (SECTIONABLE_FABRIC_KINDS.includes(row.kind) || row.reference_routed)
		&& (row.reference_routed || qtyRows.length > 6)
		&& sections.length > 1
		&& qtyRows.every((qr) => qr.section != null)
	if (!sectionable) return null
	sections.forEach((section) => delete section._diaByName)
	return { sections, asColumns: sections.length <= MAX_COLOUR_COLUMNS }
}

export function knittingInputRouteKey(qtyRowIndex, colour = null) {
	return `${qtyRowIndex}::${colour || ""}`
}

function roundQty(value) {
	return Math.round((Number(value) || 0) * 1000) / 1000
}

function contractIdentity(item, attrs, uom) {
	const sortedAttrs = Object.entries(attrs || {})
		.filter(([, value]) => value)
		.sort(([left], [right]) => left.localeCompare(right))
	return JSON.stringify([item || "", sortedAttrs, uom || ""])
}

function manualRoutes(row, entry) {
	if (isMultiColour(row)) {
		return (row.colour_options || []).flatMap((colour) =>
			(row.qty_rows || []).map((qr, qtyRowIndex) => ({
				key: knittingInputRouteKey(qtyRowIndex, colour),
				qr,
				qtyRowIndex,
				colour,
				outputQty: Number(entry.colourQtys[colour][qtyRowIndex]) || 0,
			})),
		)
	}
	return (row.qty_rows || []).map((qr, qtyRowIndex) => ({
		key: knittingInputRouteKey(qtyRowIndex),
		qr,
		qtyRowIndex,
		colour: null,
		outputQty: Number(entry.qtys[qtyRowIndex]) || 0,
	}))
}

function physicalOutput(row, entry, route) {
	const attrs = { ...(route.qr.out_attrs || {}) }
	const colour = route.colour || route.qr.knit_colour || entry.colour
	if (row.has_colour && colour) attrs.Colour = colour
	return {
		item: route.qr.output_item || row.cloth_item,
		attrs,
		uom: route.qr.output_uom || "Kg",
	}
}

function appendGrouped(groups, byKey, identity, values, member, qty) {
	let group = byKey.get(identity)
	if (!group) {
		group = { key: identity, ...values, qty: 0, members: [] }
		byKey.set(identity, group)
		groups.push(group)
	}
	group.qty += Number(qty) || 0
	group.members.push(member)
}

function buildManualKnittingContract(row, entry) {
	const receivables = []
	const receivablesByKey = new Map()
	const deliverables = []
	const deliverablesByKey = new Map()

	for (const route of manualRoutes(row, entry)) {
		const output = physicalOutput(row, entry, route)
		appendGrouped(
			receivables,
			receivablesByKey,
			contractIdentity(output.item, output.attrs, output.uom),
			output,
			{
				routeKey: route.key,
				weight: route.outputQty || Number(route.qr.program) || 0,
			},
			route.outputQty,
		)

		const quantities = entry.knittingInputQtys[route.key] || []
		;(route.qr.knitting_inputs || []).forEach((input, inputIndex) => {
			const qty = Number(quantities[inputIndex]) || 0
			appendGrouped(
				deliverables,
				deliverablesByKey,
				contractIdentity(input.item, input.attrs, input.uom),
				{ item: input.item, attrs: { ...(input.attrs || {}) }, uom: input.uom || "Kg" },
				{
					routeKey: route.key,
					inputIndex,
					inputKey: input.key,
					baseInputQty: qty,
					baseOutputQty: route.outputQty,
					qtyPerOutput: Number(input.qty_per_output) || 0,
				},
				qty,
			)
		})
	}

	for (const group of [...receivables, ...deliverables]) {
		group.qty = roundQty(group.qty)
	}
	// Show every distinct physical input/output generated by the IPD, including
	// zero-prefilled alternatives. The operator may intentionally select a dyed
	// yarn or receivable that differs from the saved Cloth Program. Only exact
	// duplicate physical variants are consolidated.
	return { receivables, deliverables }
}

function distribute(total, members, weightFor) {
	const qty = Math.max(roundQty(total), 0)
	const allocations = new Map(members.map((member) => [member, 0]))
	if (!qty || !members.length) return allocations

	let weighted = members
		.map((member) => ({ member, weight: Math.max(Number(weightFor(member)) || 0, 0) }))
		.filter(({ weight }) => weight > 0)
	if (!weighted.length) weighted = members.map((member) => ({ member, weight: 1 }))
	const totalWeight = weighted.reduce((sum, row) => sum + row.weight, 0)
	let allocated = 0
	weighted.forEach(({ member, weight }, index) => {
		const part = index === weighted.length - 1
			? roundQty(qty - allocated)
			: roundQty(qty * weight / totalWeight)
		allocated = roundQty(allocated + part)
		allocations.set(member, part)
	})
	return allocations
}

// Convert the two simple physical-item tables back to matrix routes only at
// submission time. Route weights remain hidden implementation detail needed
// for finished-colour tracking and partial-GRN yarn consumption.
export function collectManualKnittingContract(row, entry) {
	const routes = manualRoutes(row, entry)
	const outputByRoute = new Map(routes.map((route) => [route.key, 0]))
	for (const receivable of entry.manualReceivables || []) {
		const allocations = distribute(receivable.qty, receivable.members, (member) => member.weight)
		for (const [member, qty] of allocations) outputByRoute.set(member.routeKey, qty)
	}

	const inputsByRoute = new Map(routes.map((route) => [route.key, new Map()]))
	const orphanDeliverables = []
	for (const deliverable of entry.manualDeliverables || []) {
		const qty = Math.max(roundQty(deliverable.qty), 0)
		if (!qty) continue
		const active = deliverable.members.filter(
			(member) => (outputByRoute.get(member.routeKey) || 0) > 0,
		)
		if (!active.length) {
			orphanDeliverables.push(deliverable)
			continue
		}
		const allocations = distribute(qty, active, (member) => {
			const outputQty = outputByRoute.get(member.routeKey) || 0
			const savedRatio = member.baseOutputQty > 0
				? member.baseInputQty / member.baseOutputQty
				: 0
			return outputQty * (savedRatio || member.qtyPerOutput || 1)
		})
		for (const [member, inputQty] of allocations) {
			inputsByRoute.get(member.routeKey).set(member.inputIndex, {
				key: member.inputKey,
				qty: inputQty,
			})
		}
	}

	return {
		orphanDeliverables,
		routes: routes.map((route) => ({
			qty: outputByRoute.get(route.key) || 0,
			qr: route.qr,
			colour: route.colour || route.qr.knit_colour || null,
			manualInputs: (route.qr.knitting_inputs || []).map((input, inputIndex) =>
				inputsByRoute.get(route.key).get(inputIndex) || { key: input.key, qty: 0 },
			),
		})),
	}
}

export function createFabricEntries(context) {
	return (context.rows || []).map((row) => {
		const multiColour = isMultiColour(row)
		const entry = {
			colour: multiColour ? null : row.greige_colour || null,
			yarnQty: null,
			qtys: (row.qty_rows || []).map((qr) => qr.prefill ?? null),
			colourQtys: {},
			knittingInputQtys: {},
		}
		if (multiColour) {
			entry.qtys = (row.qty_rows || []).map(() => null)
			for (const colour of row.colour_options) {
				entry.colourQtys[colour] = (row.qty_rows || []).map((qr) =>
					colour === row.greige_colour ? qr.prefill ?? null : null,
				)
			}
		}
		if (row.kind === "knitting") {
			const quantities = multiColour ? Object.values(entry.colourQtys).flat() : entry.qtys
			const total = quantities.reduce((sum, qty) => sum + (Number(qty) || 0), 0)
			entry.yarnQty = Math.round(total / (Number(row.ratio) || 1) * 1000) / 1000
			;(row.qty_rows || []).forEach((qr, qtyRowIndex) => {
				const colours = multiColour ? row.colour_options : [null]
				for (const colour of colours) {
					const outputQty = multiColour
						? entry.colourQtys[colour][qtyRowIndex]
						: entry.qtys[qtyRowIndex]
					entry.knittingInputQtys[knittingInputRouteKey(qtyRowIndex, colour)] = (
						qr.knitting_inputs || []
					).map((input) => {
						const suggested = (
							!multiColour && input.prefill != null
								? Number(input.prefill)
								: (Number(outputQty) || 0) * (Number(input.qty_per_output) || 0)
						)
						return Math.round(suggested * 1000) / 1000
					})
				}
			})
			if (row.manual_io) {
				const contract = buildManualKnittingContract(row, entry)
				entry.manualDeliverables = contract.deliverables
				entry.manualReceivables = contract.receivables
			}
		}
		return entry
	})
}

// Commit a context and its editable quantities together, only after a successful
// request. A failed Fill must not erase the operator's existing data entry.
export function useFabricDeliverableContext(fetchContext) {
	const ctx = ref(null)
	const entries = ref([])
	const loading = ref(false)
	let generation = 0

	function invalidate() {
		generation++
		loading.value = false
	}

	async function load(workOrder, sourceProcess = null, { reset = false } = {}) {
		const request = ++generation
		loading.value = true
		if (reset) {
			ctx.value = null
			entries.value = []
		}
		try {
			const result = await fetchContext({ work_order: workOrder, source_process: sourceProcess })
			if (request !== generation) return false
			const next = result || { is_fabric_process: false, rows: [] }
			const nextEntries = createFabricEntries(next)
			ctx.value = next
			entries.value = nextEntries
			return true
		} catch (error) {
			if (request === generation) throw error
			return false
		} finally {
			if (request === generation) loading.value = false
		}
	}

	return { ctx, entries, loading, load, invalidate }
}
