from frappe.model.document import Document


class SDYRPItemProductionDetailPackingAssortmentAttribute(Document):
	pass


ItemProductionDetailPackingAssortmentAttribute = SDYRPItemProductionDetailPackingAssortmentAttribute
