from frappe.model.document import Document


class SDYRPItemProductionDetailPackingAttributeDetail(Document):
	pass


ItemProductionDetailPackingAttributeDetail = SDYRPItemProductionDetailPackingAttributeDetail
